notifications:
  email:
    - travis-ci@pimcore.org

sudo: false
language: php

php:
  - 7
  - 7.1
  - 7.2

services:
  - redis

addons:
  mariadb: '10.1'
  hosts:
    - pimcore-test.dev

matrix:
  include:
    - os: linux
      sudo: required
      php: 7
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      sudo: required
      php: 7.1
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      sudo: required
      php: 7.2
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      php: 7.1
      env:
          - PIMCORE_TEST_SUITE=cache
          - PIMCORE_TEST_GROUP=cache.core.redis
          - PIMCORE_TEST_SETUP_SKIP_PHP_REDIS_EXTENSION=true

cache:
  directories:
    - vendor

env:
  global:
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_CACHE_REDIS_DATABASE=1

before_install:
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

install:
  # add config templates
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp .travis/extensions.template.php var/config/extensions.php
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - composer install

before_script:
  - .travis/setup-php.sh
  - .travis/setup-functional-tests.sh

script:
  - .travis/run-tests.sh
