version: "3.3"
services:
  mysql:
    container_name: pimcore_mysql
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
    volumes:
      - database:/var/lib/mysql
  php:
    container_name: pimcore_php
    build: ./docker/php
    ports:
      - 9000:9000
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
  nginx:
    container_name: pimcore_nginx
    build: ./docker/nginx
    ports:
      - 80:80

volumes:
  database: